name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:  
      image: elementary/docker:unstable
    
    steps:
    - uses: actions/checkout@v1
 
    - name: Install Houston dependencies
      run: |
        apt update
        apt install -y libcurl3-gnutls libstdc++-6-dev npm
 
    - name: Install Houston CI
      run: npm i -g @elementaryos/houston
 
    - name: Run Houston
      run: houston ci
            --type system-app
            --name-domain io.elementary.appcenter
            --name-human AppCenter
